server:
  port: 8082
spring:
  application:
    name: consumer-user
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
    fetch-remote-regions-registry: 20 # 默认是30秒
  instance:
    prefer-ip-address: true