server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: provider-user
  datasource:
    url: jdbc:mysql://192.168.3.90:3306/cdm_db
    driver-class-name: com.mysql.jdbc.Driver
    username: cdm
    password: cdm
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30  # 租期到期时间，默认90秒
    lease-renewal-interval-in-seconds: 10  # 心跳时间间隔，默认30秒